language: python
python:
- "2.7.13"
sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    if [ ! -e Gemfile ]; then
       curl -s -o ./Gemfile 'https://gerrit.mcp.mirantis.com/gitweb?p=salt-formulas/salt-formulas-scripts.git;a=blob_plain;f=Gemfile;hb=refs/heads/master'
    fi
  - bundle install

env:
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=control-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=master-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=minion-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=minion-multi-master-failover
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=control-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=master-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=minion-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=minion-multi-master-failover
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=control-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=master-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=minion-default
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=minion-multi-master-failover
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=control-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=master-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=minion-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=minion-multi-master-failover
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=control-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=master-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=minion-default
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=minion-multi-master-failover

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
